[package]
name = "permutational"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
miette = {version = "4.2.1", features = ["fancy"]}
deunicode = "1.3.1"